// eslint-disable-next-line @typescript-eslint/no-var-requires
const swaggerAutogen = require('swagger-autogen')({ language: 'pt-BR' });

const outputFile = `./doc/swagger/doc.json`;
const endpointsFiles = [`./src/routes/index`];

const doc = {
  info: {
    version: '0.0.1',
    title: `Hivelabs - API`,
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:3333',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [{ name: 'users', description: 'user router' }],
  securityDefinitions: {
    apiKeyAuth: {
      type: 'apiKey',
      in: 'header', // can be "header", "query" or "cookie"
      name: 'X-API-KEY', // name of the header, query parameter or cookie
      description: 'any description...',
    },
  },
  definitions: {
    AddUser: {
      $name: 'Caio',
      $lastName: 'Nascimento',
      $nickname: 'nick',
      $address: 'rua sousa girão - 163',
      bio: 'bio',
    },
    UpdateUser: {
      lastName: 'Nascimento',
      address: 'rua sousa girão - 163',
    },
    UpdateNickname: {
      $nickname: 'nick',
    },
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc);
